// <auto-generated />
using System;
using Assignment_1_Dahyun_Ko.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_1_Dahyun_Ko.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20231004013956_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Assignment_1_Dahyun_Ko.Models.Program", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            ProgramId = "CP",
                            Name = "Computer Programming"
                        },
                        new
                        {
                            ProgramId = "CPA",
                            Name = "Computer Programming and Analysis"
                        },
                        new
                        {
                            ProgramId = "ITID",
                            Name = "IT Innovation and Design"
                        },
                        new
                        {
                            ProgramId = "SET",
                            Name = "Software Engineering Technology"
                        },
                        new
                        {
                            ProgramId = "BACS",
                            Name = "Bachelor of Applied Computer Science"
                        });
                });

            modelBuilder.Entity("Assignment_1_Dahyun_Ko.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("GPAScale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(1971, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bart",
                            GPA = 2.7000000000000002,
                            GPAScale = "Satisfactory",
                            LastName = "Simpson",
                            ProgramId = "CP"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(1973, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            GPA = 4.0,
                            GPAScale = "Excellence",
                            LastName = "Simpson",
                            ProgramId = "BACS"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateTime(1996, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maggie",
                            GPA = 3.1000000000000001,
                            GPAScale = "Good",
                            LastName = "Simpson",
                            ProgramId = "CPA"
                        });
                });

            modelBuilder.Entity("Assignment_1_Dahyun_Ko.Models.Student", b =>
                {
                    b.HasOne("Assignment_1_Dahyun_Ko.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });
#pragma warning restore 612, 618
        }
    }
}
